//! Turning DNS scopes into what a flat resolver wants.
//!
//! Pure, and separate from the writing, because "what would this produce?" is
//! a question worth answering without touching `/etc/resolv.conf` -- both in
//! tests and, eventually, in `ncfg plan`.
//!
//! Only the flat modes live here. A scope-capable backend renders per-domain
//! configuration and is M4's job; decision 0007 makes asking a flat mode for
//! routing domains a compile error rather than something to flatten here.

use netcfgd_model::{DnsPolicy, DnsServer};

/// One scope to deliver.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Scope<'a> {
	/// Which scope: an interface name, or `globals`.
	pub name: &'a str,
	/// What it asks for.
	pub policy: &'a DnsPolicy,
}

/// The flattened result: what a single-list resolver ends up with.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Flat {
	/// Servers, in precedence order.
	pub servers: Vec<DnsServer>,
	/// Search domains, in order.
	pub search: Vec<String>,
	/// Resolver options.
	pub options: Vec<String>,
}

/// Merge scopes into one flat answer.
///
/// Per-interface scopes come before the global one, and within each list the
/// first occurrence wins -- decision 0006 rule 4, applied to the only
/// mechanism a flat resolver has. The order of the interfaces themselves is
/// the document's, which is sorted by name, so the result is deterministic
/// rather than dependent on which interface came up first.
///
/// This is a lossy operation and that is the whole point of decision 0007: a
/// flat resolver cannot express "these servers for that domain", so the
/// compiler refuses configs that ask for it rather than letting the loss
/// happen quietly here.
#[must_use]
pub fn flatten(scopes: &[Scope<'_>]) -> Flat {
	let mut flat = Flat::default();

	// Interfaces first, globals last: a specific answer should be consulted
	// before the fallback, and a flat resolver's only notion of "specific" is
	// "earlier in the list".
	let ordered = scopes
		.iter()
		.filter(|scope| scope.name != "globals")
		.chain(scopes.iter().filter(|scope| scope.name == "globals"));

	for scope in ordered {
		for server in &scope.policy.servers {
			if !flat.servers.contains(server) {
				flat.servers.push(server.clone());
			}
		}
		for domain in &scope.policy.search {
			if !flat.search.contains(domain) {
				flat.search.push(domain.clone());
			}
		}
		for option in &scope.policy.options {
			if !flat.options.contains(option) {
				flat.options.push(option.clone());
			}
		}
	}

	flat
}

/// Render `resolv.conf`.
///
/// The three-server limit is glibc's, not netcfgd's: the resolver reads at
/// most `MAXNS` (3) nameserver lines and silently ignores the rest. Writing
/// more would look like it worked and quietly not. The extras are listed in a
/// comment instead, so somebody reading the file can see what was dropped and
/// why.
#[must_use]
pub fn resolv_conf(flat: &Flat, generator: &str) -> String {
	const MAXNS: usize = 3;
	let mut out = format!("# Generated by {generator}. Edits will be overwritten.\n");

	if !flat.search.is_empty() {
		out.push_str(&format!("search {}\n", flat.search.join(" ")));
	}
	for server in flat.servers.iter().take(MAXNS) {
		out.push_str(&format!("nameserver {}\n", server.addr));
	}
	if flat.servers.len() > MAXNS {
		out.push_str(&format!(
			"# {} further server(s) omitted: the resolver reads at most {MAXNS}\n",
			flat.servers.len() - MAXNS
		));
		for server in flat.servers.iter().skip(MAXNS) {
			out.push_str(&format!("#   {}\n", server.addr));
		}
	}
	if !flat.options.is_empty() {
		out.push_str(&format!("options {}\n", flat.options.join(" ")));
	}
	out
}

/// Render the blob `resolvconf -a <iface>` reads on stdin.
///
/// Same format as `resolv.conf`, one scope at a time, because that is the
/// interface `resolvconf(8)` defines: each subscriber hands over what it knows
/// about one interface and the implementation decides how to combine them.
/// Handing it a pre-merged file would throw away the one thing it is for.
#[must_use]
pub fn resolvconf_blob(policy: &DnsPolicy) -> String {
	let mut out = String::new();
	if !policy.search.is_empty() {
		out.push_str(&format!("search {}\n", policy.search.join(" ")));
	}
	for server in &policy.servers {
		out.push_str(&format!("nameserver {}\n", server.addr));
	}
	if !policy.options.is_empty() {
		out.push_str(&format!("options {}\n", policy.options.join(" ")));
	}
	out
}

#[cfg(test)]
mod tests {
	use super::*;
	use netcfgd_model::DnsMode;

	fn server(text: &str) -> DnsServer {
		DnsServer {
			addr: text.parse().expect("test address"),
			port: None,
			sni: None,
		}
	}

	fn policy(servers: &[&str], search: &[&str]) -> DnsPolicy {
		DnsPolicy {
			mode: DnsMode::WriteResolvConf,
			servers: servers.iter().map(|text| server(text)).collect(),
			search: search.iter().map(|text| (*text).to_owned()).collect(),
			..DnsPolicy::default()
		}
	}

	/// Interface scopes come before the global one, because a flat resolver's
	/// only notion of "more specific" is "earlier in the list".
	#[test]
	fn interface_scopes_come_before_globals() {
		let global = policy(&["1.1.1.1"], &["fallback.example"]);
		let eth0 = policy(&["10.0.0.1"], &["lan.example"]);
		let scopes = vec![
			Scope {
				name: "globals",
				policy: &global,
			},
			Scope {
				name: "eth0",
				policy: &eth0,
			},
		];

		let flat = flatten(&scopes);
		assert_eq!(
			flat.servers
				.iter()
				.map(|s| s.addr.to_string())
				.collect::<Vec<_>>(),
			["10.0.0.1", "1.1.1.1"]
		);
		assert_eq!(flat.search, ["lan.example", "fallback.example"]);
	}

	/// Decision 0006 rule 4: deduplicated, first occurrence wins.
	#[test]
	fn duplicates_keep_their_first_position() {
		let one = policy(&["10.0.0.1", "1.1.1.1"], &[]);
		let two = policy(&["1.1.1.1", "10.0.0.1"], &[]);
		let scopes = vec![
			Scope {
				name: "eth0",
				policy: &one,
			},
			Scope {
				name: "eth1",
				policy: &two,
			},
		];

		let flat = flatten(&scopes);
		assert_eq!(flat.servers.len(), 2);
		assert_eq!(flat.servers[0].addr.to_string(), "10.0.0.1");
	}

	/// glibc reads at most three nameserver lines. Writing more would look
	/// like it worked and quietly not, so the extras are commented rather than
	/// emitted -- and a reader can see what was dropped.
	#[test]
	fn beyond_three_servers_the_rest_are_commented_not_dropped_silently() {
		let many = policy(&["10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4"], &[]);
		let flat = flatten(&[Scope {
			name: "eth0",
			policy: &many,
		}]);
		let text = resolv_conf(&flat, "netcfgd test");

		let active: Vec<&str> = text
			.lines()
			.filter(|line| line.starts_with("nameserver "))
			.collect();
		assert_eq!(active.len(), 3, "glibc reads at most three");
		assert!(
			text.contains("10.0.0.4"),
			"the omitted server should still be visible: {text}"
		);
		assert!(text.contains("omitted"), "and labelled as omitted: {text}");
	}

	#[test]
	fn resolv_conf_says_who_wrote_it() {
		let flat = flatten(&[]);
		let text = resolv_conf(&flat, "netcfgd");
		assert!(text.starts_with("# Generated by netcfgd"));
		assert!(text.contains("overwritten"));
	}

	/// resolvconf takes one scope at a time; pre-merging would throw away the
	/// only thing it is for.
	#[test]
	fn a_resolvconf_blob_covers_one_scope_only() {
		let eth0 = policy(&["10.0.0.1"], &["lan.example"]);
		let blob = resolvconf_blob(&eth0);
		assert_eq!(blob, "search lan.example\nnameserver 10.0.0.1\n");
	}

	/// An empty policy renders to an empty blob rather than a header with
	/// nothing under it, so `resolvconf -a` is not handed a file that says
	/// nothing in several lines.
	#[test]
	fn an_empty_scope_renders_empty() {
		assert_eq!(resolvconf_blob(&DnsPolicy::default()), "");
	}
}
