//! A configuration file cannot take the stack out.
//!
//! `cargo fuzz` on the `config_parse` target reported an `AddressSanitizer`
//! stack-overflow: the parser descends once per `{`, and nothing bounded it.
//! The input is 3679 bytes carrying 1238 open braces and is kept verbatim in
//! `tests/deep/nested.conf` -- generated bytes rather than a tidy handwritten
//! case, because the tidy version is the one somebody later "simplifies" into
//! something that no longer reaches the recursion.
//!
//! A daemon that re-reads its configuration directory on every change is the
//! reason this matters: the crash is reachable by writing a file, and a
//! diagnostic is what a malformed file is supposed to produce.

use netcfgd_compile::{compile, NoHooks, SourceMap};

/// The exact bytes the fuzzer found, which used to exhaust the stack.
#[test]
fn the_input_that_overflowed_the_stack_now_compiles_to_a_diagnostic() {
	let text = include_str!("deep/nested.conf");
	let mut sources = SourceMap::new();
	sources.add("nested.conf", text);

	let result = compile(&sources, &mut NoHooks);
	assert!(
		result.is_err(),
		"this file is not valid and must be refused"
	);
}

/// And the refusal says what is wrong, rather than failing for some other
/// reason that happens to stop the descent.
#[test]
fn nesting_past_the_limit_is_named_as_nesting() {
	let mut text = String::new();
	for _ in 0..64 {
		text.push_str("interface eth0 {\n");
	}
	let mut sources = SourceMap::new();
	sources.add("deep.conf", &text);

	let error = compile(&sources, &mut NoHooks).expect_err("64 deep is refused");
	let message = format!("{error}");
	assert!(
		message.contains("nests more than"),
		"the diagnostic should name the nesting, and said: {message}"
	);
}

/// The other way down, which bounding blocks alone did not cover.
///
/// `parse_value` calls `parse_list` calls `parse_value`, so a run of `[`
/// recurses exactly as a run of `{` does. This is here because the first fix
/// was to blocks only, and re-running the fuzzer against it crashed again in
/// under five minutes -- the same defect down a path the block counter could
/// not see.
#[test]
fn a_run_of_open_brackets_is_refused_too() {
	let mut text = String::from("interface eth0 {\n\tdns { servers = ");
	for _ in 0..2_000 {
		text.push('[');
	}
	text.push('\n');
	let mut sources = SourceMap::new();
	sources.add("brackets.conf", &text);

	let error = compile(&sources, &mut NoHooks).expect_err("a bracket run is refused");
	let message = format!("{error}");
	assert!(
		message.contains("nests more than"),
		"the diagnostic should name the nesting, and said: {message}"
	);
}

/// A list nested to a sane depth still parses, so the bound did not simply
/// break lists.
#[test]
fn an_ordinary_nested_list_still_compiles() {
	let mut sources = SourceMap::new();
	sources.add(
		"list.conf",
		"interface eth0 {\n\tdns { servers = [\"10.0.0.1\", \"2001:db8::1\"] }\n}\n",
	);
	assert!(
		compile(&sources, &mut NoHooks).is_ok(),
		"an ordinary list must still compile"
	);
}

/// The limit is far above anything the language actually uses, so ordinary
/// configuration is untouched. Three levels is the real depth.
#[test]
fn ordinary_nesting_is_nowhere_near_the_limit() {
	let mut sources = SourceMap::new();
	sources.add(
		"ok.conf",
		"interface eth0 {\n\tconfig = \"dhcp\"\n}\ndevice eth0 {\n\tqdisc {\n\t\tkind = \"cake\"\n\t\tbandwidth = \"100mbit\"\n\t}\n}\n",
	);
	assert!(
		compile(&sources, &mut NoHooks).is_ok(),
		"a normal configuration must still compile"
	);
}
