/*
 * parse_test.c -- the grammar, the recovery, and the bound on the stack.
 *
 * WHY THIS EXISTS
 *   The parser is the thing that reads a file a person edited on a machine
 *   with no network, so two properties matter more than the shapes it
 *   accepts: it must say something useful about every mistake rather than the
 *   first, and it must not fall over on a file that is not a configuration at
 *   all. A daemon that re-reads its configuration directory whenever anything
 *   in it changes turns "the parser crashed" into "the machine has no
 *   network", and `cargo fuzz` reached that crash twice before the limit
 *   below existed.
 *
 *   So the cases here are not a sweep of the grammar. Each is a rule the
 *   language has -- a block that may be labelled or not, a list that may span
 *   lines, a statement that ends at a newline or a semicolon or a `}` -- or a
 *   defect that was found: the run of `{` that exhausted the stack, kept
 *   verbatim, and the run of `[` that did it again down a path the first fix
 *   could not see.
 */
#include "ncfg/ast.h"
#include "ncfg/base.h"
#include "ncfg/parse.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failures;

static void check(int condition, const char *what)
{
	printf("%-58s %s\n", what, condition ? "ok" : "FAILED");
	if (!condition) {
		failures++;
	}
}

/* A block lifted from `doc/netcfgd.conf.example`: the wireless three-parter,
 * which is the densest real thing in the file -- a nested block, a boolean, a
 * quoted block name and a secret reference. `lex_test.c` lexes this same
 * text, so the two modules are held against one fixture rather than two. */
static const char *const example_block =
    "device wlan0 {\n"
    "\twifi {\n"
    "\t\tautoconnect = true\n"
    "\t}\n"
    "}\n"
    "interface wlan0 {\n"
    "\tconfig = \"dhcp\"\n"
    "}\n"
    "network \"Cafe Wifi\" {\n"
    "\twifi {\n"
    "\t\tpsk = \"@secret:cafe\"\n"
    "\t}\n"
    "}\n";

/* A hook as the manual writes one: inside an `interface` block, indented,
 * with braces in the shell, and closed by a brace on a line of its own. */
static const char *const hook_with_braces =
    "interface eth0 {\n"
    "\tconfig = \"dhcp\"\n"
    "\tpost_up {\n"
    "if [ -n \"$NCFG_ADDR\" ]; then\n"
    "\techo \"up ${NCFG_IFACE}\" | logger\n"
    "fi\n"
    "}\n"
    "}\n";

/* Exactly what the lexer should have handed the parser for the hook above:
 * every line between the `{` and the closing line, byte for byte. */
static const char *const hook_with_braces_body =
    "if [ -n \"$NCFG_ADDR\" ]; then\n"
    "\techo \"up ${NCFG_IFACE}\" | logger\n"
    "fi\n";

static const char *const hook_then_more =
    "interface eth0 {\n"
    "\tpost_up {\n"
    "echo hi\n"
    "}\n"
    "\tmtu = 1500\n"
    "}\n";

/*
 * The exact bytes `cargo fuzz` found, which used to exhaust the stack.
 *
 * 3679 bytes carrying 1238 open braces, kept verbatim from
 * `crates/netcfgd-compile/tests/deep/nested.conf` -- generated bytes rather
 * than a tidy handwritten case, because the tidy version is the one somebody
 * later "simplifies" into something that no longer reaches the recursion.
 */
static const char *const fuzzed_nesting =
    "Y{}t;ut{u{uv{}t{ut{ut{a{a{arrid{}t{ut{a{at{t{ut{uv{}t{ut{ut{a{a{arrid{"
    "}t{ut{ut{Z_.Y{}t{ut{ut{a{Raut{ut{}t{ut{ut{Zba{at{t{ut{uv{}t{ut{ut{a{a{"
    "arrid{}t{ut{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}t;ut{u{at{ut{_.Y{}t{t{utt{"
    "uv{}t{uv{ut{u{t{ut{ut{_.Y{}t{ut{ut{at{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}"
    "t;ut{u{at{ut{_.Y{}t{t{utt{uv{}t{uv{ut{u{t{ut{ut{}t{ut{ut{a{a{at{t{ut{u"
    "vut{ut{}t{ut{ut{Zbaut{a{a{att{ut{a{a{arrid{}t{ut{t{ut{uvut{ut{}t{ut{ut"
    "{Zba{at{t{ut{uv{}t{ut{ut{a{a{arrid{}t{ut{a{at{t{ut{uv{}t{ut{ut{a{a{arr"
    "id{}t{ut{ut{Z_.Y{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{at"
    "{Raut{ut{}t{ut{ut{Zba{at{t{ut{uv{}t{ut{ut{a{a{arrid{}t{ut{a{at{t{uv{}t"
    "{uv{uut{u{t{ut{ut{}t{ut{ut{a{a{at{t{ut{uvut{ut{}t{ut{ut{Zbt{a{at{ut{_."
    "Y{}z{ut{ut{a{aaY{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{at"
    "{ut{_.t{_.Y{}t{ut{ut{at{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}t;ut{u{at{ut{_"
    ".Y{}z{t{ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{qt{}t{ut{Y{}t{tutt{u{t{ut{qt"
    "{}ta{at{t{ut{uvut{u{utt{uv{}t{uv{ut{u{t{ut{ut{}t{ut{utt{ut{uv{}t{ut{ut"
    "{a{t{t{aY{}t;ut{u{at{ut{_.Y{}t{t{utt{uv{}t{uv{ut{u{t{ut{ut{}t{ut{ut{a{"
    "a{at{t{ut{uvut{ut{}t{ut{ut{Zbaut{a{a{at{t{ut{uvut{ut{}t{ut{ut{Zba{at{t"
    "{ut{uv{}t{ut{ut{a{a{arrid{at{ut{_.Y{}t{t{utd{utrue{uv{ut{u{t{ut{ut{}t{"
    "ut{ut{a{a{at{t{ut{uvut{ut{}t{zy{t{a{a{arrid{}t{ut{a{at{t{ut{uv{}t{ut{u"
    "t{a{a{arrid{}t{ut{ut{Z_.Y{}t{ut{ut{a{Raut{ut{}t{ut{ut{Zba{at{t{ut{uv{}"
    "t{ut{ut{a{a{arrid{}t{ut{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}t;ut{u{at{ut{_"
    ".Y{}t{t{utt{uv{}t{uv{ut{u{t{ut{ut{_.Y{}t{ut{ut{a{Raut{ut{}t{ut{ut{Zba{"
    "at{t{ud{uv{}t{ut{ut{a{a{arrid{}t{ut{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}t;"
    "ut{u{at{ut{_.Y{}t{t{utt{uv{}t{uv{ut{u{t{ut{ut{}t{ut{ut{a{a{at{t{ut{uvu"
    "t{ut{}t{ut{ut{Zbaut{a{a{at{t{ut{uvut{ut{}t{ut{ut{Zba{at{t{ut{uv{at{t{u"
    "t{uv{}t{ut{ut{a{a{arrid{}t{ut{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}t;ut{u{a"
    "t{ut{_.Y{}t{t{utt{uv{}t{uv{ut{u{t{ut{ut{_.Y{}t{ut{ut{at{a{at{t{ut{uv{}"
    "t{ut{ut{a{t{t{aY{}t;ut{u{at{ut{_.Y{}t{t{utt{uv{}t{uv{ut{u{t{ut{ut{}t{u"
    "t{ut{a{a{at{t{ut{uvut{ut{}t{ut{ut{Zbaut{a{a{att{ut{a{a{arrid{}t{ut{t{u"
    "t{uvut{ut{}t{ut{ut{Zba{at{t{ut{uv{}t{ut{ut{a{a{arrid{}t{ut{a{at{t{ut{u"
    "v{}t{ut{ut{a{a{arrid{}t{ut{ut{Z_.Y{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{"
    "ut{a{aa{Rat{t{a{at{Raut{ut{}t{ut{ut{Zba{at{t{ut{u}t{ut{ut{a{a{arrid{}t"
    "{ut{a{at{t{ut{uv{}t{ut{ut{a{a{arrid{}t{ut{ut{Z_.Y{}t{ut{{u{t{ut{uY{}t;"
    "ut{u{at{ut{_.Y{}t{t{utt{ut{a{a{at{t{ut{uvut{ut{}t{ut{ut{Zba{at{t{ut{uv"
    "{}t{ut{ut{a{a{arrid{}t{ut{ut{Z_.t{ut{Zba{at{tZba{at{t{ut{uv{}t{ut{ut{a"
    "{a{arrid{}t{ut{ut{Z_.t{ut{Zba{at{tt{a{at{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{"
    "at{ut{_.Y{}z{t{ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{ut{}t{ut{ut{ut{uv{}t{"
    "ut{ut{a{a{arrid{}t{ut{ut{Z_.Y{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{ut{a{"
    "aaY{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{at{ut{_.Y{}z{t{"
    "ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{ut{}t{ut{ut{a{a{at{t{ut{uvut{ut{}t{u"
    "t{ut{Zbt{a{at{ut{_.Y{}z{ut{ut{a{aaY{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut"
    "{ut{a{aa{Rat{t{a{at{ut{_.Y{}z{t{ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{qt{}"
    "t{ut{ut{a{a{ata{a{at{t{ut{uvut{ut{}t{ut{ut{Zbt{a{at{ut{_.Y{}z{ut{ut{a{"
    "aaY{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{at{ut{_.Y{}z{t{"
    "ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{qt{}t{ut{ut{a{t{a{aa{Rat{t{a{at{ut{_"
    ".Y{}z{t{ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{qt{}t{ut{ut{a{a{ata{a{at{t{u"
    "t{uvut{ut{}t{ut{ut{Zbt{a{at{ut{_.Y{}z{ut{ut{a{aaY{}t{ut{ut{a{Rat{t{a{a"
    "t{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{at{ut{_.Y{}z{t{ut{_ba{at{t{ut{uv{}t{uv{"
    "uut{u{t{ut{ut{}t{ut{ut{a{a{at{t{ut{uvut{ut{}t{ut{ut{Zbt{a{at{ut{_.Y{}z"
    "{ut{ut{a{aaY{}t{ut{ut{a{Rat{t{a{at{ut{_.Y{}z{ut{ut{a{aa{Rat{t{a{at{ut{"
    "_.t{_.Y{}t{ut{ut{at{a{at{t{ut{uv{}t{ut{ut{a{t{t{aY{}t;ut{u{at{ut{_.Y{}"
    "z{t{ut{_ba{at{t{ut{uv{}t{uv{ut{u{t{ut{qt{}t{ut{Y{}t{tutt{u{t{ut{qt{}ta"
    "{at{t{ut{uvut{u{utt{uv{}t{uv{ut{u{t{ut{ut{}t{ut{ut{}t{ut{ut{Zba{at{t{u"
    "t{uv{}t{ut{t{a{a{at{t{ut{uvut{uut{at{{}";

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

/* Parse, and say what went wrong when it should not have. The caller frees
 * the file with one call, which is the whole of the ownership rule. */
static ncfg_ast_file_t *accepted(const char *text)
{
	char             message[NCFG_ERROR_MAX];
	ncfg_ast_file_t *file = NULL;

	message[0] = '\0';
	if (ncfg_parse(text, strlen(text), &file, NULL, message, sizeof(message))) {
		return file;
	}
	printf("    the parser refused it: %s\n", message);
	return NULL;
}

/*
 * Refused, *and* with something said about it.
 *
 * Every diagnostic is searched rather than only the first: recovery means the
 * file goes on being read after a mistake, so the message a case is about is
 * not always at the top. A failure carrying no sentence at all is the thing
 * `base.h`'s convention exists to prevent and is invisible to a test that
 * checks only the return value, so the count is checked too.
 */
static int refused_saying(const char *text, const char *fragment)
{
	char             message[NCFG_ERROR_MAX];
	ncfg_diags_t     diags = { NULL, 0u, 0u, 0u };
	ncfg_ast_file_t *file = NULL;
	size_t           i;
	int              found = 0;

	message[0] = '\0';
	if (ncfg_parse(text, strlen(text), &file, &diags, message, sizeof(message))) {
		ncfg_ast_file_free(file);
		printf("    it parsed, and should not have\n");
		return 0;
	}
	if (file) {
		ncfg_ast_file_free(file);
		printf("    a refusal handed back a tree anyway\n");
		return 0;
	}
	if (message[0] == '\0' || diags.count == 0u) {
		printf("    refused with nothing said\n");
		ncfg_diags_free(&diags);
		return 0;
	}
	for (i = 0u; i < diags.count; i++) {
		if (diags.at[i].message && strstr(diags.at[i].message, fragment)) {
			found = 1;
		}
	}
	if (!found) {
		printf("    wanted a message about \"%s\", got:\n", fragment);
		for (i = 0u; i < diags.count; i++) {
			printf("      %s\n", diags.at[i].message);
		}
	}
	ncfg_diags_free(&diags);
	return found;
}

/* The `index`th statement of a list, or NULL where there is none. */
static const ncfg_ast_item_t *item_at(const ncfg_ast_items_t *items, size_t index)
{
	if (!items || index >= items->count) {
		return NULL;
	}
	return items->at[index];
}

/* The `index`th statement, where it is a block with this head and label. A
 * NULL `label` means the block must have none, which is a different thing
 * from having an empty one. */
static const ncfg_ast_block_t *block_at(const ncfg_ast_items_t *items, size_t index,
    const char *head, const char *label)
{
	const ncfg_ast_item_t *item = item_at(items, index);

	if (!item || item->kind != NCFG_AST_ITEM_BLOCK) {
		return NULL;
	}
	if (!item->as.block.head || strcmp(item->as.block.head, head) != 0) {
		return NULL;
	}
	if (!label) {
		return item->as.block.label ? NULL : &item->as.block;
	}
	if (!item->as.block.label || strcmp(item->as.block.label, label) != 0) {
		return NULL;
	}
	return &item->as.block;
}

/* The `index`th statement, where it is `key = "string"`. */
static int assignment_is(const ncfg_ast_items_t *items, size_t index, const char *key,
    const char *value)
{
	const ncfg_ast_item_t *item = item_at(items, index);

	if (!item || item->kind != NCFG_AST_ITEM_ASSIGNMENT) {
		return 0;
	}
	if (!item->as.assignment.key || strcmp(item->as.assignment.key, key) != 0) {
		return 0;
	}
	if (!item->as.assignment.value || item->as.assignment.value->kind != NCFG_AST_STRING) {
		return 0;
	}
	return item->as.assignment.value->string
	    && strcmp(item->as.assignment.value->string, value) == 0;
}

/* `count` copies of `piece`, NUL-terminated; NULL if it will not fit. The
 * caller frees it. */
static char *repeated(const char *piece, size_t count)
{
	size_t length = strlen(piece);
	char  *text = malloc(length * count + 1u);
	size_t i;

	if (!text) {
		return NULL;
	}
	for (i = 0u; i < count; i++) {
		memcpy(text + i * length, piece, length);
	}
	text[length * count] = '\0';
	return text;
}

/* Whether a file of `depth` nested blocks, opened and closed, parses. */
static int nesting_of_depth_parses(size_t depth)
{
	char *opens = repeated("a {\n", depth);
	char *closes = repeated("}\n", depth);
	char *text = NULL;
	int   parsed = 0;

	if (opens && closes) {
		text = malloc(strlen(opens) + strlen(closes) + 1u);
	}
	if (text) {
		ncfg_ast_file_t *file;

		memcpy(text, opens, strlen(opens) + 1u);
		memcpy(text + strlen(opens), closes, strlen(closes) + 1u);
		file = accepted(text);
		parsed = file != NULL;
		ncfg_ast_file_free(file);
	}
	free(text);
	free(opens);
	free(closes);
	return parsed;
}

int main(void)
{
	/* THE SHAPE THAT COMES OUT. What everything above the parser reads. */
	{
		ncfg_ast_file_t       *file;
		const ncfg_ast_block_t *block;
		const ncfg_ast_block_t *inner;

		file = accepted("");
		check(file && file->items.count == 0u,
		    "an empty file is a file with no statements in it");
		ncfg_ast_file_free(file);

		file = accepted("interface eth0 {\n\tconfig = \"dhcp\"\n}\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		check(file && file->items.count == 1u && block && !block->overrides
		    && block->items.count == 1u
		    && assignment_is(&block->items, 0u, "config", "dhcp"),
		    "a head, a label and a key reach the tree as written");
		ncfg_ast_file_free(file);

		/* Every node carries a span because every diagnostic points at
		 * one; a tree that knew only what was written and not where
		 * would make each of them useless. */
		file = accepted("interface eth0 {\n\tconfig = \"dhcp\"\n}\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		check(block && block->span.line == 1u && block->span.column == 1u
		    && block->items.at[0]->as.assignment.span.line == 2u
		    && block->items.at[0]->as.assignment.span.column == 2u,
		    "and each of them knows the line and column it was on");
		ncfg_ast_file_free(file);

		file = accepted(example_block);
		check(file && file->items.count == 3u,
		    "a real block from the example file is three statements");
		block = file ? block_at(&file->items, 0u, "device", "wlan0") : NULL;
		inner = block ? block_at(&block->items, 0u, "wifi", NULL) : NULL;
		check(inner && inner->items.count == 1u
		    && inner->items.at[0]->kind == NCFG_AST_ITEM_ASSIGNMENT
		    && inner->items.at[0]->as.assignment.value->kind == NCFG_AST_BOOL
		    && inner->items.at[0]->as.assignment.value->boolean == 1,
		    "the radio's policy nests, and `true` is a boolean");
		block = file ? block_at(&file->items, 1u, "interface", "wlan0") : NULL;
		check(block && assignment_is(&block->items, 0u, "config", "dhcp"),
		    "the interface block beside it says what the link should be");
		/* The quoted label is the case a bare-identifier rule would
		 * miss: an SSID has spaces in it, and `network Cafe Wifi` is
		 * not something anybody can write. */
		block = file ? block_at(&file->items, 2u, "network", "Cafe Wifi") : NULL;
		inner = block ? block_at(&block->items, 0u, "wifi", NULL) : NULL;
		check(inner && assignment_is(&inner->items, 0u, "psk", "@secret:cafe"),
		    "and a label may be a quoted string with a space in it");
		ncfg_ast_file_free(file);

		/* A block with no label is a different thing from one with an
		 * empty label, and the tree keeps them apart: `global` takes
		 * none, and `network "" { }` is a mistake somebody else has to
		 * refuse by name. */
		file = accepted("global {\n\ton_drift = \"reconcile\"\n}\n");
		check(file && block_at(&file->items, 0u, "global", NULL),
		    "a block that takes no label has none rather than an empty one");
		ncfg_ast_file_free(file);

		file = accepted("network \"\" {\n}\n");
		block = file ? block_at(&file->items, 0u, "network", "") : NULL;
		check(block && block->label && block->label_length == 0u,
		    "and an empty label is a label, for whoever refuses it later");
		ncfg_ast_file_free(file);
	}

	/* OVERRIDE, which is the whole of the layering rule in the language. */
	{
		ncfg_ast_file_t        *file;
		const ncfg_ast_block_t *block;

		file = accepted("override interface eth0 { config = \"10.0.0.1/24\" }\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		check(block && block->overrides,
		    "`override` marks the block rather than becoming one");
		/* The span is the block's head, not the `override`: the reader
		 * of a diagnostic is looking for the block. */
		check(block && block->span.column == 10u,
		    "and the block still points at its own head");
		ncfg_ast_file_free(file);

		file = accepted("interface eth0 { config = \"dhcp\" }\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		check(block && !block->overrides, "a block without it is not marked");
		ncfg_ast_file_free(file);

		check(refused_saying("override\n", "expected a block after `override`"),
		    "`override` with nothing after it is named");
		check(refused_saying("override override override\n",
		    "expected `{` to open `override`"),
		    "and `override` is not itself a block head");
	}

	/* TERMINATORS. A statement ends at a newline, a semicolon, or the `}`
	 * that closes the block it is in -- and the parser must not care
	 * which was written. */
	{
		ncfg_ast_file_t        *file;
		const ncfg_ast_block_t *block;

		file = accepted("device eth0 { mtu = 9000 } # jumbo\n"
		        "interface eth0 { config = \"dhcp\" }\n");
		check(file && file->items.count == 2u,
		    "a one-line block ends its statement at the `}`");
		block = file ? block_at(&file->items, 0u, "device", "eth0") : NULL;
		check(block && block->items.count == 1u
		    && block->items.at[0]->as.assignment.value->kind == NCFG_AST_NUMBER
		    && block->items.at[0]->as.assignment.value->number == 9000,
		    "and a comment after it is not part of anything");
		ncfg_ast_file_free(file);

		file = accepted("global { hostname = \"a\"; on_drift = \"reconcile\" }\n");
		block = file ? block_at(&file->items, 0u, "global", NULL) : NULL;
		check(block && block->items.count == 2u,
		    "a semicolon separates statements exactly as a newline does");
		ncfg_ast_file_free(file);

		file = accepted("\n\n\nglobal {\n\n\n\thostname = \"a\"\n\n}\n\n");
		block = file ? block_at(&file->items, 0u, "global", NULL) : NULL;
		check(file && file->items.count == 1u && block && block->items.count == 1u,
		    "blank lines are not statements");
		ncfg_ast_file_free(file);

		file = accepted("hostname = \"a\"");
		check(file && file->items.count == 1u,
		    "and a file may end without a terminator at all");
		ncfg_ast_file_free(file);

		check(refused_saying("device eth0 { mtu = 1500 1600 }\n",
		    "expected end of statement, found a number"),
		    "two values on one line is a mistake, not a list");
	}

	/* LISTS. The bracketed value, which is the second way to nest. */
	{
		ncfg_ast_file_t        *file;
		const ncfg_ast_block_t *block;
		const ncfg_ast_value_t *value;

		file = accepted("interface eth0 {\n"
		        "\tconfig = [\"dhcp\", \"2001:db8::10/64\"]\n"
		        "}\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		value = block && block->items.count == 1u
		    ? block->items.at[0]->as.assignment.value
		    : NULL;
		check(value && value->kind == NCFG_AST_LIST && value->entries.count == 2u
		    && value->entries.at[1]->kind == NCFG_AST_STRING
		    && strcmp(value->entries.at[1]->string, "2001:db8::10/64") == 0,
		    "a list is its entries, in the order written");
		ncfg_ast_file_free(file);

		/* A long list is unreadable on one line, so a terminator
		 * inside brackets is whitespace -- including the one after a
		 * trailing comma, which is how a list is edited. */
		file = accepted("interface eth0 {\n"
		        "\tconfig = [\n"
		        "\t\t\"10.0.0.1/24\",\n"
		        "\t\t\"10.0.1.1/24\",\n"
		        "\t]\n"
		        "}\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		value = block && block->items.count == 1u
		    ? block->items.at[0]->as.assignment.value
		    : NULL;
		check(value && value->kind == NCFG_AST_LIST && value->entries.count == 2u,
		    "a list may span lines and end with a comma");
		ncfg_ast_file_free(file);

		file = accepted("a = []\n");
		value = file && file->items.count == 1u
		    ? file->items.at[0]->as.assignment.value
		    : NULL;
		check(value && value->kind == NCFG_AST_LIST && value->entries.count == 0u,
		    "an empty list is a list rather than nothing");
		ncfg_ast_file_free(file);

		file = accepted("a = [1, true, \"x\", [2]]\n");
		value = file && file->items.count == 1u
		    ? file->items.at[0]->as.assignment.value
		    : NULL;
		check(value && value->entries.count == 4u
		    && value->entries.at[0]->kind == NCFG_AST_NUMBER
		    && value->entries.at[0]->number == 1
		    && value->entries.at[1]->kind == NCFG_AST_BOOL
		    && value->entries.at[2]->kind == NCFG_AST_STRING
		    && value->entries.at[3]->kind == NCFG_AST_LIST,
		    "every kind of value may be an entry, a list included");
		ncfg_ast_file_free(file);

		check(refused_saying("a = [1 2]\n", "expected `,` or `]` in list"),
		    "an entry that follows another without a comma is named");
		check(refused_saying("a = [1,\n", "expected a value, found end of file"),
		    "and a list that runs off the end of the file is named");
	}

	/* VALUES, and the one production that is not a value. */
	{
		ncfg_ast_file_t        *file;
		const ncfg_ast_value_t *value;

		file = accepted("a = -1\nb = 0\nc = false\n");
		value = file && file->items.count == 3u
		    ? file->items.at[0]->as.assignment.value
		    : NULL;
		check(value && value->kind == NCFG_AST_NUMBER && value->number == -1,
		    "a negative number is a number rather than two tokens");
		value = file ? file->items.at[2]->as.assignment.value : NULL;
		check(value && value->kind == NCFG_AST_BOOL && value->boolean == 0,
		    "`false` is a boolean and not a name");
		ncfg_ast_file_free(file);

		/* A string may hold a NUL, so the length travels with it: a
		 * value that stopped at the NUL would be a shorter one than
		 * the operator wrote and nobody would ever see it was short. */
		file = accepted("a = \"x\\ny\"\n");
		value = file && file->items.count == 1u
		    ? file->items.at[0]->as.assignment.value
		    : NULL;
		check(value && value->string_length == 3u
		    && memcmp(value->string, "x\ny", 3u) == 0,
		    "a string arrives with its escapes resolved and its length");
		ncfg_ast_file_free(file);

		check(refused_saying("interface eth0 { config = }\n",
		    "expected a value, found `}`"),
		    "an assignment with nothing on the right is named");
		check(refused_saying("= = =\n", "expected a statement, found `=`"),
		    "and a line that starts with punctuation is not a statement");
		check(refused_saying("interface eth0 { config \"dhcp\" }\n",
		    "expected `{` to open `config`"),
		    "a key with a value and no `=` is read as a block, and refused");
	}

	/* INCLUDE. The compiler opens no files, which is what keeps the front
	 * end testable with no filesystem at all. */
	{
		ncfg_ast_file_t       *file;
		const ncfg_ast_item_t *item;

		file = accepted("include \"conf.d/extra.conf\"\n");
		item = file ? item_at(&file->items, 0u) : NULL;
		check(item && item->kind == NCFG_AST_ITEM_INCLUDE
		    && strcmp(item->as.include.path, "conf.d/extra.conf") == 0
		    && item->as.include.span.column == 1u,
		    "an include is a node with a path and nothing opened");
		ncfg_ast_file_free(file);

		check(refused_saying("include eth0\n",
		    "expected a quoted path after `include`"),
		    "an include of something unquoted is named");
		check(refused_saying("include\n", "expected a quoted path after `include`"),
		    "and so is an include of nothing");
	}

	/* HOOKS. The one irregular production: the body is shell and is never
	 * tokenised, so what the lexer scanned is what the tree must hold. */
	{
		ncfg_ast_file_t        *file;
		const ncfg_ast_block_t *block;
		const ncfg_ast_item_t  *item;

		file = accepted(hook_with_braces);
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		item = block ? item_at(&block->items, 1u) : NULL;
		check(item && item->kind == NCFG_AST_ITEM_HOOK
		    && strcmp(item->as.hook.phase, "post_up") == 0,
		    "a hook block is a phase and a body, inside the block it is in");
		/*
		 * Byte for byte, not "contains": a hook body is shell, and
		 * re-indenting it or dropping the newline off its last line
		 * changes what the shell does. The `}` of the `if` is in it
		 * and the closing line is not.
		 */
		check(item && item->as.hook.body
		    && strcmp(item->as.hook.body, hook_with_braces_body) == 0
		    && item->as.hook.body_length == strlen(hook_with_braces_body),
		    "and its body is the lexer's bytes, unmodified");
		check(item && item->as.hook.span.line == 3u
		    && item->as.hook.span.column == 2u,
		    "the hook's span is the phase keyword, where the reader looks");
		ncfg_ast_file_free(file);

		/* The parser steps out of the token stream for the body and
		 * back in afterwards, so configuration below a hook is still
		 * configuration. */
		file = accepted(hook_then_more);
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		check(block && block->items.count == 2u
		    && block->items.at[0]->kind == NCFG_AST_ITEM_HOOK
		    && block->items.at[1]->kind == NCFG_AST_ITEM_ASSIGNMENT,
		    "and the parser steps back into the token stream after it");
		ncfg_ast_file_free(file);

		/* `on <event>` reaches the phases with no keyword of their
		 * own, and the phase is the event as written: a phase this
		 * build does not know has to arrive as text, or the
		 * diagnostic that names it can only say something was wrong. */
		file = accepted("interface eth0 {\n\ton lease {\necho leased\n}\n}\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		item = block ? item_at(&block->items, 0u) : NULL;
		check(item && item->kind == NCFG_AST_ITEM_HOOK
		    && strcmp(item->as.hook.phase, "lease") == 0
		    && strcmp(item->as.hook.body, "echo leased\n") == 0,
		    "`on lease` is a hook whose phase is the event");
		ncfg_ast_file_free(file);

		file = accepted("interface eth0 {\n\tpost_up {\n\t}\n}\n");
		block = file ? block_at(&file->items, 0u, "interface", "eth0") : NULL;
		item = block ? item_at(&block->items, 0u) : NULL;
		check(item && item->kind == NCFG_AST_ITEM_HOOK && item->as.hook.body
		    && item->as.hook.body[0] == '\0'
		    && item->as.hook.body_length == 0u,
		    "an empty hook body is empty rather than absent");
		ncfg_ast_file_free(file);

		/* `device` is a phase name nowhere and a labelled block
		 * everywhere, so a collision between the two tables must
		 * resolve to the block -- otherwise the commonest block in the
		 * language would be read as shell. */
		file = accepted("device eth0 {\n\tmtu = 9000\n}\n");
		check(file && block_at(&file->items, 0u, "device", "eth0"),
		    "a block whose head could be a phase is still a block");
		ncfg_ast_file_free(file);

		check(refused_saying("interface eth0 {\n\tpost_up {\necho hi\n",
		    "unterminated hook body"),
		    "a hook body that never closes is named");
		check(refused_saying("interface eth0 {\n\ton {\n}\n}\n",
		    "expected an event name after `on`"),
		    "and `on` with no event is named");
		check(refused_saying("post_up = 1\n", "expected `{` after `post_up`"),
		    "a phase used as a key is named too");
	}

	/* UNCLOSED THINGS, which must be named rather than producing a
	 * cascade of complaints about what follows them. */
	{
		check(refused_saying("interface eth0 {\n\tconfig = \"dhcp\"\n",
		    "unclosed block `interface`"),
		    "a block that never closes is named");
		check(refused_saying("interface eth0\n", "expected `{` to open `interface`"),
		    "a block head with no body is named");
		/*
		 * A string may span lines, which the grammar requires because
		 * the netifrc spelling puts several entries in one value. The
		 * cost is that a missing quote swallows the rest of the file,
		 * so the position has to be the opening quote: reporting where
		 * the lexer gave up sends the reader to a line that is not the
		 * mistake.
		 */
		{
			char             message[NCFG_ERROR_MAX];
			ncfg_diags_t     diags = { NULL, 0u, 0u, 0u };
			ncfg_ast_file_t *file = NULL;
			const char      *text
			    = "interface eth0 {\n\tconfig = \"dhcp\n\tmtu = 1500\n}\n";
			char             rendered[NCFG_ERROR_MAX];

			check(!ncfg_parse(text, strlen(text), &file, &diags, message,
			      sizeof(message))
			    && diags.count > 0u && diags.at[0].span.line == 2u
			    && diags.at[0].span.column == 11u,
			    "a runaway string points at its opening quote");
			ncfg_diag_render(diags.count ? &diags.at[0] : NULL, "netcfgd.conf",
			    rendered, sizeof(rendered));
			check(strncmp(rendered, "netcfgd.conf:2:11: ", 19u) == 0
			    && strstr(rendered, "unterminated string"),
			    "and a rendered diagnostic names file, line and column");
			ncfg_diags_free(&diags);
		}
	}

	/* RECOVERY. Four mistakes should take one edit round, not four. */
	{
		char             message[NCFG_ERROR_MAX];
		ncfg_diags_t     diags = { NULL, 0u, 0u, 0u };
		ncfg_ast_file_t *file = NULL;
		const char      *text = "a = ]\nb = ]\nc = ]\nd = \"fine\"\n";

		check(!ncfg_parse(text, strlen(text), &file, &diags, message, sizeof(message))
		    && diags.count == 3u && diags.at[0].span.line == 1u
		    && diags.at[1].span.line == 2u && diags.at[2].span.line == 3u,
		    "every mistake is reported, not only the first");
		ncfg_diags_free(&diags);

		/*
		 * Past the ceiling only the count moves. The Rust kept every
		 * diagnostic, which is right in a test harness and wrong in a
		 * daemon: nobody reads the sixty-fifth message, and a
		 * diagnostic per token is a file-sized allocation bought with
		 * a malformed file. `total` is what lets a caller say how many
		 * more there were rather than pretending there were none.
		 */
		{
			char            *many = repeated("a = ]\n", 100u);
			ncfg_diags_t     lots = { NULL, 0u, 0u, 0u };
			ncfg_ast_file_t *nothing = NULL;

			if (many) {
				(void)ncfg_parse(many, strlen(many), &nothing, &lots, message,
				    sizeof(message));
			}
			check(many && lots.count == (size_t)NCFG_DIAGS_MAX && lots.total == 100u,
			    "a hundred mistakes are counted and the first sixty-four kept");
			ncfg_ast_file_free(nothing);
			ncfg_diags_free(&lots);
			free(many);
		}

		/* And a caller that wants only the sentence may pass no
		 * diagnostics at all, which must not change what is refused. */
		file = NULL;
		message[0] = '\0';
		check(!ncfg_parse(text, strlen(text), &file, NULL, message, sizeof(message))
		    && message[0] != '\0' && !file,
		    "a caller that wants only the sentence still gets one");
	}

	/*
	 * NESTING. A configuration file cannot take the stack out.
	 *
	 * `cargo fuzz` on the `config_parse` target reported an
	 * `AddressSanitizer` stack-overflow: the parser descends once per `{`
	 * and nothing bounded it. A daemon that re-reads its configuration
	 * directory on every change is why it matters -- the crash is
	 * reachable by writing a file, and a diagnostic is what a malformed
	 * file is supposed to produce.
	 */
	{
		char *text;

		/*
		 * The exact bytes the fuzzer found: refused, by reaching the
		 * end of them rather than by dying on the way. The Rust test
		 * asks only that this is an error; here the nesting bound is
		 * checked to be the thing that stopped the descent, because a
		 * parse that fell over for some other reason on the way would
		 * satisfy the weaker claim and still be a crash waiting for
		 * the next input.
		 */
		{
			char             message[NCFG_ERROR_MAX];
			ncfg_diags_t     diags = { NULL, 0u, 0u, 0u };
			ncfg_ast_file_t *file = NULL;
			int              refused;
			size_t           nesting = 0u;
			size_t           i;

			refused = !ncfg_parse(fuzzed_nesting, strlen(fuzzed_nesting), &file,
			    &diags, message, sizeof(message));
			for (i = 0u; i < diags.count; i++) {
				if (strstr(diags.at[i].message, "nests more than")) {
					nesting++;
				}
			}
			check(refused && !file && strlen(fuzzed_nesting) == 3679u
			    && nesting > 0u,
			    "the input that overflowed the stack is now a diagnostic");
			ncfg_ast_file_free(file);
			ncfg_diags_free(&diags);
		}

		/* And the refusal says what is wrong, rather than failing for
		 * some other reason that happens to stop the descent. */
		text = repeated("interface eth0 {\n", 64u);
		check(text && refused_saying(text, "nests more than"),
		    "nesting past the limit is named as nesting");
		free(text);

		/*
		 * The other way down, which bounding blocks alone did not
		 * cover: `parse_value` -> `parse_list` -> `parse_value`
		 * recurses exactly as a run of `{` does. The first fix was to
		 * blocks only and re-running the fuzzer against it crashed
		 * again in under five minutes.
		 */
		text = repeated("[", 2000u);
		if (text) {
			char *brackets = malloc(strlen(text) + 64u);

			if (brackets) {
				(void)snprintf(brackets, strlen(text) + 64u,
				    "interface eth0 {\n\tdns { servers = %s\n", text);
				check(refused_saying(brackets, "nests more than"),
				    "a run of open brackets is refused as nesting too");
				free(brackets);
			}
		}
		free(text);

		/* The bound did not simply break lists, or blocks. */
		{
			ncfg_ast_file_t *file = accepted(
			    "interface eth0 {\n"
			    "\tdns { servers = [\"10.0.0.1\", \"2001:db8::1\"] }\n"
			    "}\n");

			check(file != NULL, "an ordinary nested list still parses");
			ncfg_ast_file_free(file);
		}
		{
			/* Three levels is the real depth of the language:
			 * `device` holds `qdisc` holds its keys. The limit is
			 * roughly ten times that, so no real configuration
			 * comes near it. */
			ncfg_ast_file_t *file = accepted(
			    "interface eth0 {\n\tconfig = \"dhcp\"\n}\n"
			    "device eth0 {\n\tqdisc {\n\t\tkind = \"cake\"\n"
			    "\t\tbandwidth = \"100mbit\"\n\t}\n}\n");

			check(file != NULL, "ordinary nesting is nowhere near the limit");
			ncfg_ast_file_free(file);
		}

		/* The limit itself, pinned from both sides: a change to it
		 * that nobody meant should fail here rather than in a fuzzer. */
		check(nesting_of_depth_parses((size_t)NCFG_MAX_NESTING_DEPTH),
		    "exactly the limit is accepted");
		text = repeated("a {\n", (size_t)NCFG_MAX_NESTING_DEPTH + 1u);
		check(text && refused_saying(text, "nests more than"),
		    "and one deeper is refused");
		free(text);
	}

	/*
	 * ADVERSARIAL INPUT. A configuration file is input the daemon reads
	 * with privileges, so no shape of it may crash, hang or leak. This is
	 * the cheap deterministic stand-in for a fuzz target rather than a
	 * replacement for one; under the sanitizers it also proves the error
	 * paths free what they built.
	 */
	{
		struct {
			const char *text;
			size_t      length;
		} seeds[] = {
			{ "", 0u },
			{ "\0", 1u },
			{ "{", 1u },
			{ "}", 1u },
			{ "[", 1u },
			{ "\"", 1u },
			{ "\"\\", 2u },
			{ "interface", 9u },
			{ "interface {", 11u },
			{ "interface eth0 { config = }", 27u },
			{ "= = =", 5u },
			{ "a = [[[[[[[[", 12u },
			{ "a = 99999999999999999999999999", 30u },
			{ "a = -", 5u },
			{ "post_up {", 9u },
			{ "on {", 4u },
			{ "override", 8u },
			{ "override override override", 26u },
			{ "include", 7u },
			/* A byte-order mark, and a character outside the basic
			 * plane as a label: both are bytes the lexer has rules
			 * about and the parser has none. */
			{ "\xef\xbb\xbfinterface eth0 {}", 21u },
			{ "interface \xf0\x9f\x98\x80 {}", 17u },
			{ "a = \"\\q\"", 8u },
			{ "# comment with no newline", 25u },
			{ "interface eth0 { dns = 1 }", 26u }
		};
		size_t count = sizeof(seeds) / sizeof(seeds[0]);
		size_t total = 0u;
		size_t i;
		char  *combined;

		for (i = 0u; i < count; i++) {
			char             message[NCFG_ERROR_MAX];
			ncfg_diags_t     diags = { NULL, 0u, 0u, 0u };
			ncfg_ast_file_t *file = NULL;

			message[0] = '\0';
			/* Any outcome is acceptable except a crash -- and
			 * except a refusal with nothing said, which is the one
			 * failure `base.h`'s convention forbids outright. */
			if (!ncfg_parse(seeds[i].text, seeds[i].length, &file, &diags, message,
			    sizeof(message))
			    && message[0] == '\0') {
				printf("    seed %u refused with nothing said\n",
				    (unsigned int)i);
				failures++;
			}
			ncfg_ast_file_free(file);
			ncfg_diags_free(&diags);
			total += seeds[i].length + 1u;
		}
		check(1, "no seed crashes the parser, and none refuses in silence");

		/* And the same seeds concatenated, which reaches states no
		 * single seed does. */
		combined = malloc(total + 1u);
		if (combined) {
			size_t at = 0u;

			for (i = 0u; i < count; i++) {
				memcpy(combined + at, seeds[i].text, seeds[i].length);
				at += seeds[i].length;
				combined[at] = '\n';
				at++;
			}
			{
				ncfg_ast_file_t *file = NULL;
				char             message[NCFG_ERROR_MAX];

				(void)ncfg_parse(combined, at, &file, NULL, message,
				    sizeof(message));
				ncfg_ast_file_free(file);
			}
			free(combined);
			check(1, "nor do all of them run together");
		}
	}

	/* DESCRIBING A TREE, which is the other half of "expected X, found Y"
	 * for everything built on top of this. */
	{
		ncfg_ast_file_t        *file = accepted("global { a = 1 }\n"
		                    "interface eth0 { b = \"x\" }\n");
		const ncfg_ast_block_t *global = file ? block_at(&file->items, 0u, "global", NULL)
		                      : NULL;
		const ncfg_ast_block_t *interface
		    = file ? block_at(&file->items, 1u, "interface", "eth0") : NULL;
		char                    described[64];

		ncfg_ast_block_describe(interface, described, sizeof(described));
		check(strcmp(described, "interface eth0") == 0,
		    "a labelled block describes itself with its label");
		ncfg_ast_block_describe(global, described, sizeof(described));
		check(strcmp(described, "global") == 0, "and one with no label without one");
		check(global && interface && !ncfg_ast_block_same_key(global, interface)
		    && ncfg_ast_block_same_key(interface, interface),
		    "two blocks are the same block only by head and label together");
		check(interface
		    && strcmp(ncfg_ast_value_describe(
		              interface->items.at[0]->as.assignment.value),
		           "a string")
		        == 0
		    && global
		    && strcmp(ncfg_ast_value_describe(
		              global->items.at[0]->as.assignment.value),
		           "a number")
		        == 0,
		    "a value is described rather than quoted back");
		ncfg_ast_file_free(file);
	}

	/* Freeing what was never filled in is nothing, which is the rule every
	 * error path in the parser is written on. */
	{
		ncfg_diags_t diags = { NULL, 0u, 0u, 0u };

		ncfg_ast_file_free(NULL);
		ncfg_ast_item_free(NULL);
		ncfg_ast_value_free(NULL);
		ncfg_diags_free(&diags);
		ncfg_diags_free(&diags);
		ncfg_diags_free(NULL);
		check(1, "freeing an empty tree, twice, costs nothing");
	}

	if (failures == 0) {
		printf("parse_test: all checks passed\n");
	} else {
		printf("parse_test: %d check(s) failed\n", failures);
	}
	return failures == 0 ? 0 : 1;
}
